source 'https://github.com/CocoaPods/Specs'

xcodeproj 'TomboAFNetworking Tests'
workspace '../TomboAFNetworking'
inhibit_all_warnings!

def import_pods
  pod 'OCMock', '~> 2.1.1'
  pod 'Expecta', '~> 0.2.1'
  pod 'TomboAFNetworking', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'OS X Tests'
  import_pods
end
